# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 27 Mar 2011 15:27:16 +0000
*               @ALL          1
*               @user         8
