<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: washedfrere
 * Date: Sun, 27 Mar 2011 15:39:07 +0000
 */

$conf['title'] = 'dudad.es';
$conf['start'] = 'dudad.es';
$conf['lang'] = 'es';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['updatecheck'] = 0;

// end auto-generated content
